DROP SCHEMA IF EXISTS EMPRESA;
CREATE SCHEMA IF NOT EXISTS EMPRESA;
USE EMPRESA;

CREATE TABLE IF NOT EXISTS departamentos (
  id_departamento INT UNSIGNED NOT NULL AUTO_INCREMENT,
  sigla VARCHAR(10) NOT NULL,
  nome VARCHAR(50) NOT NULL,
  PRIMARY KEY (id_departamento)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS funcionarios (
  id_funcionario INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(45) NOT NULL,
  dt_nascimento DATE,
  dt_admissao DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  sexo CHAR(1) NOT NULL,
  salario DECIMAL(8,2),
  id_departamento INT UNSIGNED NOT NULL,
  PRIMARY KEY (id_funcionario),
  CONSTRAINT fk_FUNCIONARIOS_DEPARTAMENTOS
    FOREIGN KEY (id_departamento)
    REFERENCES departamentos (id_departamento)
) ENGINE=InnoDB;

# INSERE OS DEPARTAMENTOS
INSERT INTO departamentos (sigla, nome) VALUES ('RH', 'Recursos Humanos');
INSERT INTO departamentos (sigla, nome) VALUES ('CPD', 'Centro de Processamento de Dados');
INSERT INTO departamentos (sigla, nome) VALUES ('Contabil', 'Depto. de Contabilidade');
INSERT INTO departamentos (sigla, nome) VALUES ('FINANC', 'Depto. Financeiro');
INSERT INTO departamentos (sigla, nome) VALUES ('PES', 'Depto. Pessoal');

# INSERE OS FUNCIONARIOS
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Daniel Petry','1959-06-02','M','5235.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Leila Zavarize','1959-07-24','F','1027.2','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Henrique Tabajara ','1966-11-06','M','4697.4','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luis Carlos Steimer','1970-06-24','M','5028.9','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Glauco Caruso','1973-04-17','M','1133.2','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Alex Amann','1973-09-10','M','3635.5','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Paula Poeta','1974-09-12','F','5118.6','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Milene Zardo','1974-12-14','F','4460.4','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Andrea Rammé','1975-05-08','F','4222.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Andréa Grecco','1975-05-11','F','1224.3','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Sancler','1975-06-29','M','4143.9','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rafael Franskowiak','1975-11-11','M','3522.2','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Jaderson Gaewski','1975-11-21','M','3122.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Fabiano Reis','1976-04-23','M','5365.6','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Tejard','1976-05-21','M','3351.1','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luciane Scopel','1976-06-14','F','2170','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Raquel Oliveira','1976-07-01','F','3266.3','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Beto Dalmolin','1976-09-18','M','3490.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Daniel Bueno','1977-01-06','M','1638.8','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Daniel LaPorta','1977-06-15','M','3695.1','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Elisandra Rossi','1977-09-16','F','1306.9','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rafael Barbosa','1978-04-23','M','1039.2','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Lu Slomka','1978-07-28','F','4149.2','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Alester Klaus','1978-09-21','M','3165.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Juliana Andrade','1978-09-30','F','4446.3','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Maico Bergamin','1978-10-04','M','3597.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Lucieli Rosa','1978-10-27','F','5594.3','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rachel Vanin','1978-12-01','F','4584.4','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rodrigo Jaú','1978-12-30','M','3500.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Sabrina Schultz','1979-03-21','F','5523.6','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Fran Zanon','1979-06-06','F','3540.1','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Tulio Vedana','1979-06-23','M','4035.2','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Renata Burttet','1979-09-25','F','2696.7','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Sabrina Wilhelm','1979-10-16','F','4439.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Pierre Do Valle Moreira','1979-11-10','M','5224.9','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Adriano Dilda','1980-01-29','M','3464.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Manu Balliana Maciel','1980-05-10','F','5628.8','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Viviane Almada','1980-08-13','F','4313.4','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Renata Orth','1980-09-04','F','4128.2','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Camila Macedo','1980-10-16','F','5284.1','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Janaina Olsson','1981-01-12','F','3247.7','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Madelaine Novello','1981-02-05','F','4565.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Anna de La Rocha ','1981-02-28','F','3335.4','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Guilherme Luz Tortorella','1981-04-20','M','1597','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marcelo Lopes','1981-05-03','M','4560.2','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Claudia Zago','1981-05-11','F','4674.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rafaela Zanol','1981-06-05','F','5078.3','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marcelo Lubisco','1981-07-10','M','1206.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gabriela Hartmann','1981-08-01','F','4285.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Michele Gubert','1981-08-16','F','5371.4','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Carlo Porto','1981-09-05','M','3512.6','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Quincas Machado','1981-09-09','M','1285.7','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marcos Estimado','1982-02-15','M','2567.1','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Tatiana Andrade','1982-04-26','F','4043.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Vanessa Martins','1982-05-16','F','1433.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Juliano Oster','1982-05-22','M','1435.9','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Antonela','1982-05-27','F','4045.6','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ana Paske','1982-06-16','F','4103','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ricardo Fernandes','1982-07-09','M','5477.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ricardo Fernandes','1982-07-09','M','4453.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Miguel Luis Mansinho Schmitt','1982-07-14','M','5515.8','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('João Pedro Fischer','1982-07-22','M','2637.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Lucas Pretto','1982-08-30','M','3062.1','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Fernanda Evangelista','1982-09-07','F','2682.2','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Andre Aragão','1982-09-26','M','2591.2','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gabriel Canella','1982-10-12','M','5617.8','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Emiliano Fischer','1982-10-23','M','5027.9','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marcela Braga','1982-10-28','F','3299.6','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Cassiano Kruger','1982-10-30','M','4077.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gunter ','1982-11-03','M','2160.3','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Tassiana Arbiza','1982-11-23','F','5603.6','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Greicy Finger','1982-12-31','F','4677.3','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Narjara Stein','1983-01-26','F','3106','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Leia Yaffit','1983-02-22','F','1455.2','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Dayana  Dasenbrock','1983-02-23','F','4313.2','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Denise Rossatto','1983-04-27','F','1302.1','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Martina Oliveira','1983-05-26','F','2412.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Lídia Dalmaso','1983-07-09','F','2119.3','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Thiago Dahmer','1983-07-12','M','4666.4','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gustavo Sana','1983-08-17','M','5522.7','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Suelen Debon','1983-08-26','F','4468.6','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Alice Floriano','1983-09-21','F','2326.2','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Vinícius Fraga','1983-09-25','M','5441.3','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bárbara Rocha','1984-01-10','F','4539.4','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Monica Sosnoski','1984-02-05','F','2154.8','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Francisco Gassen','1984-03-07','M','3319.8','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marcela Vaz','1984-03-23','F','3056.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rafaela Poloni','1984-03-30','F','2061.4','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Flavio Suhre ','1984-04-21','M','4586.7','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Pablo Oliveira','1984-06-01','M','5344.8','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Juliana Rizzatto','1984-06-11','F','5371.8','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gisiane Fiuza','1984-06-16','F','3057.3','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Alberto Rosa','1984-07-04','M','2597.6','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Renata Piccolli','1984-07-21','F','1127.7','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Joao Vicente Reinelli Nedeff','1984-08-12','M','4664','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Candice Carvalho','1984-08-24','F','3588.1','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Alexandre Laykowsky','1984-09-09','M','3383.7','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Guilherme Zanchi','1984-12-22','M','5668.6','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bruno Faria','1984-12-24','M','3550.9','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rafael Ferrari','1984-12-26','M','1509','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Fefa Batista','1984-12-31','F','4092.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Paulo Leal','1985-01-16','M','1518.4','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ken Sorgi','1985-02-03','M','1478.4','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Aline Scherer','1985-02-06','F','3154.9','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Julio Acosta','1985-02-22','M','1146.7','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Eduardo Kronbauer','1985-02-23','M','3100.1','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('William Carvalho','1985-02-23','M','2313.2','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Katia Kuczynski','1985-03-26','F','5310.6','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('André Braun ','1985-04-19','M','1628.8','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Pedro de Oliveira','1985-05-09','M','1467.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luciano Devitt','1985-05-29','M','4160.1','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Caroline Bacchi','1985-06-30','F','3402.2','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Vagner Camargo','1985-09-09','M','4212.3','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Monica Benini','1985-10-11','F','5149.3','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Diego Carvalho','1985-11-09','M','2560.1','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Aline Antunes','1985-11-19','F','5178.6','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luiza Ruckert','1985-12-03','F','3345.7','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Tanise Amon','1985-12-05','F','4384.8','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Larissa Lunardi','1985-12-20','F','2281.6','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Lucas Aguiar','1985-12-23','M','1468.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Priscila Machado','1986-01-04','F','2202.6','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Daniel Ló','1986-02-17','M','2043.2','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Thiago Ló','1986-02-17','M','1165.5','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Victor Tarik  Guerra','1986-02-25','M','1245.8','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Débora Ávila','1986-03-27','F','2297.3','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Mateus Schroeder','1986-04-08','M','1130.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Jivago Santinni','1986-05-17','M','4156.8','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Jonathas Moraes','1986-05-20','M','5062.2','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Antônio Barth','1986-05-23','M','2122.9','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bárbara Henn','1986-06-27','F','2567.2','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gustavo Schmitt','1986-08-12','M','3090.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Cristiane Schmidt','1986-08-22','F','2545.8','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Maycom Arenhardt','1986-09-08','M','4136.1','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rafaela Tomasi','1986-09-30','F','1028','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marcelo Longhi','1986-12-25','M','4531.7','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Vinicius Teixeira','1987-01-05','M','2293.9','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Leonardo Franke','1987-02-10','M','5572.1','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Carolina Lindner','1987-02-11','F','5291.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Patrícia Fleck','1987-02-18','F','2036.2','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Juliana Roehrs','1987-03-23','F','5172.2','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Agatha Franke','1987-04-07','F','5387.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ramona Zanon','1987-05-15','F','5131.9','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Veronica Zardo','1987-05-28','F','1598.8','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Giovanna Araújo','1987-05-29','F','3032.3','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Benazira Djoco','1987-06-04','F','4021.6','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Seidl','1987-06-12','F','5166.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Paula Helwanger','1987-06-22','F','5597.8','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Mona','1987-06-28','F','1589.1','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Grazi Galardão ','1987-07-14','F','3635.9','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Nicole Feilstrecker','1987-07-23','F','4150.7','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Nadia Blauth','1987-07-29','F','1109.1','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Elisa Kich','1987-08-31','F','3186.8','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Andressa Queiroz','1987-09-18','F','2546.7','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marina Juchen','1987-09-20','F','5362.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Renan Veiga','1987-11-05','M','4661.3','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ricardo Fischer','1987-12-05','M','4015.9','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rafael Penteado Pacheco Costa','1987-12-11','M','2226.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Tay Vargas','1987-12-24','F','4093.4','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Anauê Pinotti','1988-01-04','F','5417.4','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Mariana Coldebella','1988-01-23','F','2325','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gabriel Meirelles','1988-01-25','M','2040.2','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Diogo Bordin ','1988-02-08','M','5299.7','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Francielly Costa','1988-02-09','F','2359.5','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gabriela Markus ','1988-02-20','F','2268.2','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Wagner Carniel','1988-02-25','M','5262.4','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Nils Madenach','1988-03-14','M','4675.6','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Carla Persch','1988-05-20','F','4383.6','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Camila Paiva','1988-06-21','F','3340.1','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Valentina Asmus','1988-07-20','F','4269','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Janaina Andrade','1988-08-15','F','5671.1','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Júlia Marin','1988-08-16','F','1590.1','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Daniella Novaes','1988-08-20','F','1425','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Samantha Pinotti','1988-09-19','F','2550.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Stéphanie Custódio','1988-09-23','F','4469.6','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Kelly Gisch','1988-10-20','F','4139.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Graziela Largura','1988-10-31','F','3679.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luane Doebber','1988-11-18','F','5600.6','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Joice Cardoso','1988-11-22','F','3209.9','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Priscila Chagas','1988-11-24','F','2466.1','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('William Bond','1988-12-09','M','2119.5','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ton Andreazza ','1988-12-23','M','1141.5','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Nathan Azevedo','1988-12-26','M','5239.4','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Katryna','1989-01-19','F','5512.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luisa Mund','1989-02-02','F','4216','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Anderson Santos','1989-02-15','M','2564.6','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Thyelli Yogui','1989-03-16','F','2079.9','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Charlenne ','1989-04-12','F','5057','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('João Stefanello ','1989-04-14','M','3315.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Daniele Kreling','1989-04-24','F','2626.2','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Raphaela Sirena','1989-05-16','F','2418.8','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Thailan Reginatto','1989-08-01','M','3291','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bruna Jaroceski','1989-09-06','F','2494.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Julia Guerra','1989-09-12','F','3064.3','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Diana Graña','1989-09-23','F','3084','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Mariana Bier','1989-09-27','F','3583.1','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Caroline Saldanha','1989-09-29','F','1290.8','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gustavo Hess','1989-10-26','M','3388.5','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Anderson Wenzel','1989-11-06','M','5473.4','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Carolina Baseggio','1989-11-27','F','3265.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Darline Campos','1989-12-05','F','3178.6','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Daniel Moser Ramos','1990-01-01','M','1212.2','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Camila Koch','1990-01-25','F','5520.1','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Jonatas Trevisan Zanette','1990-02-12','M','1389.1','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Thiago Hahn','1990-02-16','M','1220.8','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bianca Arioli','1990-03-17','F','4069.3','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Camila Salvador','1990-03-20','F','4285.4','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Catiane Lauser','1990-04-26','F','1073.1','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Everton Henke','1990-04-28','M','5439.1','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Joana Souza','1990-05-24','F','5397','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marina Makemba','1990-06-19','F','3125.8','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luciane Cassol Vieira','1990-07-22','F','3270.6','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bruna Rabelo','1990-07-23','F','5446','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Adriane Scherer','1990-08-20','F','3326.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Seidy Nonose','1990-08-23','M','1093.3','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Karine Carvalho ','1990-09-15','F','4434','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Priscila Ott ','1990-09-21','F','5696.7','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rafael Ourives','1990-09-27','M','2245.1','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Nathalia Gomes','1990-09-30','F','4218.4','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marcelo Lima','1990-10-14','M','3162','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Maira Peres','1990-11-26','F','3136.7','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Cassiano Weirich','1990-12-03','M','4374.2','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Duannee Cerutti','1990-12-22','F','4070.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Isadora Feijó','1990-12-26','F','2569.2','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Roger Fernandes','1990-12-30','M','3290.6','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Eduarda Kappel','1991-01-11','F','3062.7','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Karen Schroder ','1991-01-30','F','1237.7','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Fabio Souza','1991-02-06','M','2050.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Jessica Barbosa da Silva','1991-02-27','F','4158.6','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Paulo Berner','1991-03-03','M','2558','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bárbara Stapasolla','1991-03-05','F','5249.3','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Davi Rodrigues','1991-03-25','M','4539.6','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luiza Piletti','1991-03-25','F','2014.7','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Karina Belloli','1991-04-08','F','3659.8','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Juliana Conte','1991-04-10','F','2352.7','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Thais Correa ','1991-04-25','F','2621.8','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Adriano Becker','1991-04-27','M','3458.2','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Jéssica Amaral','1991-04-30','F','3329.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Guilherme Nunes Anziliero','1991-05-07','M','1574.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Samen dos Santos Paulino','1991-05-18','F','3296.2','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Lara Córdova','1991-06-08','F','4571.1','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ana Claudia Caldatto','1991-06-09','F','4484','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rosi De Mattia','1991-06-19','F','3491.7','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Angélica Zimmer','1991-06-22','F','1158.8','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Vitória Fortes','1991-07-07','F','1589.1','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Isadora Pretto','1991-07-14','F','4231.2','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Jessica da Costa','1991-07-19','F','1073.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Lisiane Hahn','1991-08-02','F','1630.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Carolina Sanchi','1991-08-05','F','3514.3','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Emmilyn','1991-08-18','F','5277.5','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Priscila Friedrich','1991-08-21','F','5232','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Brenda Bortolon','1991-08-26','F','4222.5','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Jenniffer Garofali','1991-08-29','F','1587.3','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Camila Fernandes','1991-09-09','F','1194.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Daniela Ott','1991-09-17','F','2539.1','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Keli Fiorin','1991-09-28','F','4470','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Manuela Teixeira ','1991-10-05','F','5596.4','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ronédi Engroff','1991-10-07','F','3632.9','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Nathana Schilling ','1991-10-30','F','5434','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Juliana Mueller','1991-10-31','F','2492.7','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Augusto Hoeller','1991-11-22','M','3116.4','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Roberto Bofill','1991-11-25','M','3254.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Sara Oss ','1991-11-30','F','3455.1','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Jennifer Duarte','1992-01-12','F','3353.3','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Vivian Blankenheim','1992-01-28','F','3672.6','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marthina Brandt','1992-01-31','F','1685.4','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luã do Valle','1992-02-12','M','5144.6','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gabriella Soltys','1992-03-06','F','5077.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rodrigo Weber','1992-03-08','M','3168.4','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Daiane Baron ','1992-03-31','F','1621.4','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Carolina Dlugokenski','1992-04-06','F','1385.1','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gabriella Seidl','1992-04-13','F','5451.9','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Vitoria Bisognin','1992-04-19','F','4133.6','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Christian Reginato','1992-04-26','M','1154.1','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Felipe Toscan','1992-04-28','M','2425.8','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Helena Peixoto','1992-05-08','F','1581.8','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Jéssica Aguiar','1992-05-23','F','2217.3','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marine Hein ','1992-05-24','F','3662.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Antoniela Rodriguez','1992-06-15','F','3121.3','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luiza Lorellay','1992-06-25','F','3680.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bárbara Heck ','1992-07-13','F','3266.2','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('William Jagnow','1992-08-24','M','1113.9','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bruna Schwartz','1992-08-27','F','1059.9','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Juliana Bohm','1992-09-09','F','5291.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Emanuel Picoli ','1992-10-16','M','2210.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gregory Stuani','1992-10-20','M','4022.7','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luisa Nava','1992-11-04','F','3573.8','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luísa Brenner ','1992-11-12','F','3286.3','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Lucas Grillo','1992-11-13','M','2520','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Nicolle Schneider','1992-12-08','F','1223','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Vitoria Carvalho','1992-12-09','F','3666','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Alexandre Gralak','1992-12-12','M','1475.9','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Antônio Dalla-Lana','1992-12-19','M','2648.7','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Camila Grando ','1992-12-19','F','3046.3','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Amanda Araujo','1992-12-25','F','1114.3','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bruna Feltes','1993-01-13','F','4223.6','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Cintia Senna Dias','1993-01-20','F','4426.1','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bruna Diniz','1993-01-22','F','2209.1','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Flavia de Araujo Silva','1993-02-06','F','1497.1','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Roberta Lorenz','1993-02-12','F','3313.2','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luiz Felipe de Oliveira','1993-02-16','M','1025.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Henrique Vasconcellos','1993-03-04','M','2481.4','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Sayonara Veras','1993-03-12','F','2199.8','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Graziele Vieira','1993-04-13','F','2152.9','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Mariana Pesenti','1993-05-02','F','5617.1','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Leonardo Perroco','1993-05-02','M','3673','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Sarah Teixeira','1993-05-20','F','3682','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luiza Collet','1993-06-07','F','2549.9','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Stephanie Souza','1993-06-17','F','1367.8','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Daiana Stein','1993-06-28','F','1218.1','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Patrícia Selbach','1993-06-29','F','4689.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Patricia Padilha ','1993-09-09','F','3184.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Sasha Schenkel','1993-09-16','F','2412.6','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Thainah Mazin','1993-09-26','F','3019.2','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Dines Audrey','1993-09-28','F','2618.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Annabel','1993-10-11','F','1585.7','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Tiago Ott ','1993-10-12','M','4148.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Karine Marschall','1993-10-22','F','4484.8','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Lais Chiappin','1993-10-25','F','4516','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Giovanna Gonzatto','1993-11-23','F','2232.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Pedro Gelpi','1993-11-28','M','3241.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Patricia Brandt','1993-12-24','F','4132','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ana Paula Oliveira','1993-12-29','F','2573.5','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Leticia Wagner','1994-01-15','F','5260.1','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bruna Dadalt','1994-01-21','F','4358.4','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Milena Fernandes','1994-03-18','F','3678.8','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rafaela Caobelli','1994-03-30','F','3351.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Carolina Vidal','1994-04-04','F','1254.6','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Júlia Segatto','1994-04-12','F','1259.4','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Letícia Kuhn','1994-04-13','F','1093.3','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Amanda Mueller Costa','1994-04-14','F','3626.5','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Alina Klein','1994-04-19','F','5641.8','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Brenda Kamchen','1994-05-21','F','4690.9','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ana Ferron','1994-05-23','F','5195.2','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ana Carolina','1994-05-23','F','5415.9','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luiza Reck','1994-05-29','F','3356.6','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Sabrina De Nardi','1994-07-10','F','3319','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Annelize Biansini','1994-07-21','F','1509','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Maicon dos Santos','1994-07-21','M','3043.2','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Henrique D`Ávila','1994-07-30','M','3324.7','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Letícia Scherer','1994-08-10','F','3384.7','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Flavio Weber','1994-08-14','M','5647.4','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Cristian Fin','1994-09-03','M','5436.2','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Tamires Duarte','1994-09-08','F','3282','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Lucas dos Santos','1994-09-17','M','5344','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Andressa Haas','1994-10-13','F','2617.4','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Eduarda Weber ','1994-10-23','F','4256.9','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Francielle Mariah','1994-11-30','F','4039.4','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Guilherme Mattarollo','1994-12-04','M','3174.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Cris Oliveira','1994-12-04','F','5043.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Katiane Arenhardt','1994-12-09','F','3265','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Fernanda Zucchi ','1994-12-19','F','4469.8','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Manuella Cardoso','1995-01-17','F','3615.8','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Arthur Jobim','1995-01-25','M','2247.6','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Matheus Soares','1995-01-25','M','3130.9','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Larissa Monteiro ','1995-02-15','F','2229.4','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Susana Monteiro','1995-02-15','F','2309.4','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Jandaia Bortolini Marcon','1995-02-24','F','2228','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Alexia Utz','1995-03-05','F','4268.6','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Julia de la Rocha','1995-03-05','F','3244.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Tainara Kuyven','1995-04-01','F','5393.3','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Sabrina Scherer ','1995-04-06','F','4162.7','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luisa Brandt','1995-04-08','F','2378.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Aline Schneider','1995-04-26','F','5233.1','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gabriela Ehlerth','1995-06-25','F','1561.4','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Elis Caglioni','1995-08-15','F','2245.2','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Carolina Linck','1995-08-22','F','1119','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Carolina Zanella','1995-08-23','F','2480.3','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Douglas Graeff','1995-09-03','M','5612.9','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Francielle Reis ','1995-09-18','F','2041.1','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Nestor Zaparte','1995-12-27','M','4199.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Sabrina Gessner','1996-01-01','F','5353.7','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Fernanda Mincarone','1996-01-08','F','3679.8','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Nina Bach','1996-01-12','F','3160.6','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Flavia Surdi','1996-01-19','F','5548.1','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Victoria Michaelsen - Joice JeJ','1996-01-22','F','1642.8','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Juliana Schulz','1996-02-21','F','3582.2','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Pamela Schmidt','1996-02-23','F','1314.9','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Emily Spricigo','1996-02-29','F','5123.2','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luisa Ferrari','1996-03-11','F','1063.3','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Suellyn Scheffer','1996-03-15','F','2687.2','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Mayra Urach','1996-03-19','F','4557.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Alice Coninck','1996-04-12','F','2455.9','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('João Pedro de Castilhos','1996-05-02','M','2354','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Victor Dellorto','1996-05-31','M','3271.7','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Karen Krein','1996-06-02','F','4072.1','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Nicole Goldschmidt','1996-06-28','F','1660.3','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Valentina Marrone','1996-07-22','F','5161.2','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Brenda Nickele','1996-08-03','F','3124.8','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ana Tondin','1996-08-06','F','2207.1','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Juliana Schumacher','1996-08-26','F','1316.1','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marina Streit','1996-08-27','F','1328.3','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Lízia Bueno','1996-08-29','F','1479.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Caroline Milani','1996-09-11','F','3312.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Eduarda Altenhofer','1996-11-16','F','4069.1','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Brenda Bandeira','1996-11-21','F','5342.4','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Victoria Albuquerque','1996-12-10','F','3592.4','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Naiara Aguiar','1996-12-26','F','4255.4','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Juliana Homem','1997-02-09','F','3015.3','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Adriana Tyllmann','1997-03-27','F','1452.9','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('William Fink','1997-04-07','M','2356.3','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Fabiana Santos','1997-04-12','F','3469.4','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Alan Camargo ','1997-04-26','M','5285.8','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bianca Dautartas','1997-05-07','F','5086.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Sabrina Cristina Geib','1997-05-13','F','5680.7','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Ana Clara Gandolfi','1997-05-23','F','1022.9','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Matheus Strasburg','1997-06-13','M','3286.4','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gabriela Wandscher','1997-06-23','F','1420.7','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Adriene Iannone de Lima','1997-07-07','F','2192.7','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Julia Cardones','1997-07-22','F','2410.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Amanda Oleinick','1997-08-15','F','3419.7','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Victoria Komorowski','1997-09-02','F','4539.3','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Monalisa Menezes','1997-09-24','F','4544.5','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Maiara Biberg','1997-11-02','F','5398.9','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Luciana de Almeida','1997-11-17','F','1201.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Joana De Almeida','1997-11-17','F','3643.9','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Alice Scussel ','1997-11-28','F','2149.4','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Natalia Schmitt','1997-12-02','F','5537.5','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Anna Julia Rodrigues','1998-01-02','F','1371.8','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Fran Mentges','1998-01-03','F','2077.4','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Leticia Guedes','1998-01-16','F','2252','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Zaka Kappel','1998-02-21','M','2641.2','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Milena Zardo','1998-03-10','F','4140.3','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Maicon Reichert','1998-03-17','M','5640.8','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Mateus Reichert','1998-03-17','M','1295.3','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Isadora Comunello','1998-03-28','F','3539.2','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Yasmin Hamad','1998-03-30','F','3605.3','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Amanda Souza','1998-04-09','F','5538.3','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bernardo Assmann','1998-05-05','M','4131.8','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Alicia Franz','1998-08-07','F','2442.6','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Vitoria Brodt','1998-09-20','F','5590.2','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Giovanna Pilla Severo ','1998-10-24','F','1531.5','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Carol Zimmermann','1998-12-16','F','2289.3','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Melissa Simon','1999-01-18','F','3157.6','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Matheus Fajardo ','1999-01-26','M','3536.8','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Adriane Stein','1999-02-11','F','4474.7','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Rafaela Pretto','1999-03-15','F','4308.5','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Natalia Bado','1999-04-06','F','1131.6','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Leticia Simsen','1999-05-05','F','2518','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bianca Faoro','1999-05-07','F','1115.7','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Nicoli Delavy','1999-06-18','F','3338.7','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gabriela Gomes','1999-07-06','F','5697.1','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gianne Raupp Vianna (acompanhamento)','1999-08-27','F','4075.2','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Bibiana Bitello','1999-10-14','F','4432.3','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Andressa Flach','1999-11-02','F','1220.1','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Manoela Araujo Ribeiro Lino','1999-12-07','F','2217','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Evelin Campos','2000-01-07','F','3196','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Natalia Gobbi','2000-01-11','F','4049.3','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Marina Ryff','2000-01-21','F','2424','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gabrielle Bonfanti','2000-03-24','F','2511.6','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Matheus Mazzoni','2000-04-23','M','4103.5','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gustavo Capitão','2000-06-07','M','4616.2','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Isadora Cadore','2000-07-11','F','1122.4','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Julia Oliveira','2000-07-16','F','2619.4','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Lauren Nunes','2000-09-15','F','5589.3','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Amanda Marques ','2000-10-20','F','5189.7','5');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Joana Lazzarotto Milani','2000-11-16','F','4411.6','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Natália Lawall','2000-12-12','F','4462.6','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Matheus Montenegro','2001-02-14','M','1203.6','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Carolina Damiani','2001-11-22','F','3225.4','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Suelen Schmorantz','2002-01-09','F','3172.1','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Jadi ','2002-04-09','F','1688.3','1');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Gaby Stein','2002-05-18','F','3042.5','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Kamile Gonçalves','2003-05-18','F','2132.1','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, salario, id_departamento) VALUES ('Fernanda Contini','2010-02-01','F','5615.4','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, id_departamento) VALUES ('André Bonatto','1959-06-02','M','4');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, id_departamento) VALUES ('Julia Paula Hickmman','1984-04-02','F','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, id_departamento) VALUES ('Luciana Feijó','1984-08-31','F','3');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, id_departamento) VALUES ('Caio Gouvea','2009-08-31','M','2');
INSERT INTO funcionarios (nome, dt_nascimento, sexo, id_departamento) VALUES ('Cauê Gouvea','2008-05-20','M','2');

DROP TABLE IF EXISTS TELEFONES;

# CRIAÇÃO DA TABELA ADICIONAL
CREATE TABLE IF NOT EXISTS TELEFONES (
	id_telefone INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ddd VARCHAR(3) NOT NULL,
    numero VARCHAR(15) NOT NULL,
    operadora VARCHAR(10),
    tipo VARCHAR(20) NOT NULL,
    PRIMARY KEY (id_telefone)
) ENGINE=InnoDB;

# ALTERAÇÃO DA TABELA ADICIONAL PARA FOREIGN KEY
ALTER TABLE TELEFONES
	ADD id_funcionario INT UNSIGNED NOT NULL,
    ADD CONSTRAINT fk_FUNC
		FOREIGN KEY (id_funcionario)
        REFERENCES FUNCIONARIOS(id_funcionario);

# EXECUTE COM: CTRL + SHIFT + ENTER
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('51','99888-1212','VIVO','CELULAR','8');
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('51','99856-1215','VIVO','CELULAR','8');
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('51','99955-2213','CLARO','CELULAR','8');
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('54','3030-2225','OI','RESIDENCIAL','46');
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('54','98556-2323','GVT','CELULAR','46');
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('11','2323-6965','GVT','COMERCIAL','75');
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('21','4212-4556','OI','RESIDENCIAL','87');
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('51','98523-6964','TIM','CELULAR','103');
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('51','95877-7841','TIM','CELULAR','103');
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('51','3483-1755','VIVO','RESIDENCIAL','122');
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('11','92565-6464','CLARO','CELULAR','139');
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('54','922568-7853','CLARO','CELULAR','175');
INSERT INTO TELEFONES (ddd, numero, operadora, tipo, id_funcionario) VALUES ('54','3044-2559','OI','RESIDENCIAL','175');

# CRIA TABELA DE USUARIOS DO CRUD
USE EMPRESA;
CREATE TABLE IF NOT EXISTS USUARIOS (
	id_usuario INT UNSIGNED NOT NULL AUTO_INCREMENT,
    usuario VARCHAR(20) NOT NULL,
    senha VARCHAR(50) NOT NULL,
    PRIMARY KEY (id_usuario)
) ENGINE=INNODB;

INSERT INTO USUARIOS (usuario, senha) VALUES ('admin', '21232f297a57a5a743894a0e4a801fc3');



